export const DOMAINWATCHER_SHOW_RESET = 'DOMAINWATCHER_SHOW_RESET'
export const DOMAINWATCHER_SHOW_SET_ERROR = 'DOMAINWATCHER_SHOW_SET_ERROR'
export const DOMAINWATCHER_SHOW_SET_RETRIEVED = 'DOMAINWATCHER_SHOW_SET_RETRIEVED'
export const DOMAINWATCHER_SHOW_TOGGLE_LOADING = 'DOMAINWATCHER_SHOW_TOGGLE_LOADING'
