export const MEDIA_SHOW_RESET = 'MEDIA_SHOW_RESET'
export const MEDIA_SHOW_SET_ERROR = 'MEDIA_SHOW_SET_ERROR'
export const MEDIA_SHOW_SET_RETRIEVED = 'MEDIA_SHOW_SET_RETRIEVED'
export const MEDIA_SHOW_TOGGLE_LOADING = 'MEDIA_SHOW_TOGGLE_LOADING'
