export const USER_STATISTICS_RESET = 'USER_STATISTICS_RESET'
export const USER_STATISTICS_SET_ERROR = 'USER_STATISTICS_SET_ERROR'
export const USER_STATISTICS_SET_RETRIEVED = 'USER_STATISTICS_SET_RETRIEVED'
export const USER_STATISTICS_TOGGLE_LOADING = 'USER_STATISTICS_TOGGLE_LOADING'
