export const WALLET_SHOW_RESET = 'WALLET_SHOW_RESET'
export const WALLET_SHOW_SET_ERROR = 'WALLET_SHOW_SET_ERROR'
export const WALLET_SHOW_SET_RETRIEVED = 'WALLET_SHOW_SET_RETRIEVED'
export const WALLET_SHOW_TOGGLE_LOADING = 'WALLET_SHOW_TOGGLE_LOADING'
