export const CONFIG_RESET = 'CONFIG_RESET'
export const CONFIG_SET_ERROR = 'CONFIG_SET_ERROR'
export const CONFIG_SET_CONFIGS = 'CONFIG_SET_CONFIGS'
export const CONFIG_TOGGLE_LOADING = 'CONFIG_TOGGLE_LOADING'
