export const EMAILMESSAGE_SHOW_RESET = 'EMAILMESSAGE_SHOW_RESET'
export const EMAILMESSAGE_SHOW_SET_ERROR = 'EMAILMESSAGE_SHOW_SET_ERROR'
export const EMAILMESSAGE_SHOW_SET_RETRIEVED = 'EMAILMESSAGE_SHOW_SET_RETRIEVED'
export const EMAILMESSAGE_SHOW_TOGGLE_LOADING = 'EMAILMESSAGE_SHOW_TOGGLE_LOADING'
