export const SMSMESSAGE_DELETE_RESET = 'SMSMESSAGE_DELETE_RESET'
export const SMSMESSAGE_DELETE_SET_ERROR = 'SMSMESSAGE_DELETE_SET_ERROR'
export const SMSMESSAGE_DELETE_SET_DELETED = 'SMSMESSAGE_DELETE_SET_DELETED'
export const SMSMESSAGE_DELETE_TOGGLE_LOADING = 'SMSMESSAGE_DELETE_TOGGLE_LOADING'
