export const RESET = 'PROVINCE_LIST_RESET'
export const SET_ITEMS = 'PROVINCE_LIST_SET_ITEMS'
export const SET_ERROR = 'PROVINCE_LIST_SET_ERROR'
export const TOGGLE_LOADING = 'PROVINCE_LIST_TOGGLE_LOADING'
