export const COUNTY_SHOW_RESET = 'COUNTY_SHOW_RESET'
export const COUNTY_SHOW_SET_ERROR = 'COUNTY_SHOW_SET_ERROR'
export const COUNTY_SHOW_SET_RETRIEVED = 'COUNTY_SHOW_SET_RETRIEVED'
export const COUNTY_SHOW_TOGGLE_LOADING = 'COUNTY_SHOW_TOGGLE_LOADING'
