export const SMSMESSAGE_SHOW_RESET = 'SMSMESSAGE_SHOW_RESET'
export const SMSMESSAGE_SHOW_SET_ERROR = 'SMSMESSAGE_SHOW_SET_ERROR'
export const SMSMESSAGE_SHOW_SET_RETRIEVED = 'SMSMESSAGE_SHOW_SET_RETRIEVED'
export const SMSMESSAGE_SHOW_TOGGLE_LOADING = 'SMSMESSAGE_SHOW_TOGGLE_LOADING'
