export const RESET = 'PROVINCE_CITIES_RESET'
export const SET_ITEMS = 'PROVINCE_CITIES_SET_ITEMS'
export const SET_ERROR = 'PROVINCE_CITIES_SET_ERROR'
export const TOGGLE_LOADING = 'PROVINCE_CITIES_TOGGLE_LOADING'
