export const RESET = 'EMAILTEMPLATE_LIST_RESET'
export const SET_ITEMS = 'EMAILTEMPLATE_LIST_SET_ITEMS'
export const SET_ERROR = 'EMAILTEMPLATE_LIST_SET_ERROR'
export const TOGGLE_LOADING = 'EMAILTEMPLATE_LIST_TOGGLE_LOADING'
