export const DOMAIN_STATISTICS_RESET = 'DOMAIN_STATISTICS_RESET'
export const DOMAIN_STATISTICS_SET_ERROR = 'DOMAIN_STATISTICS_SET_ERROR'
export const DOMAIN_STATISTICS_SET_RETRIEVED = 'DOMAIN_STATISTICS_SET_RETRIEVED'
export const DOMAIN_STATISTICS_TOGGLE_LOADING = 'DOMAIN_STATISTICS_TOGGLE_LOADING'
