export const DOMAIN_SHOW_RESET = 'DOMAIN_SHOW_RESET'
export const DOMAIN_SHOW_SET_ERROR = 'DOMAIN_SHOW_SET_ERROR'
export const DOMAIN_SHOW_SET_RETRIEVED = 'DOMAIN_SHOW_SET_RETRIEVED'
export const DOMAIN_SHOW_TOGGLE_LOADING = 'DOMAIN_SHOW_TOGGLE_LOADING'
