export const EMAILMESSAGE_DELETE_RESET = 'EMAILMESSAGE_DELETE_RESET'
export const EMAILMESSAGE_DELETE_SET_ERROR = 'EMAILMESSAGE_DELETE_SET_ERROR'
export const EMAILMESSAGE_DELETE_SET_DELETED = 'EMAILMESSAGE_DELETE_SET_DELETED'
export const EMAILMESSAGE_DELETE_TOGGLE_LOADING = 'EMAILMESSAGE_DELETE_TOGGLE_LOADING'
