export const STATISTICS_DOMAINS_RESET = 'STATISTICS_DOMAINS_RESET'
export const STATISTICS_DOMAINS_SET_ERROR = 'STATISTICS_DOMAINS_SET_ERROR'
export const STATISTICS_DOMAINS_SET_RETRIEVED = 'STATISTICS_DOMAINS_SET_RETRIEVED'
export const STATISTICS_DOMAINS_TOGGLE_LOADING = 'STATISTICS_DOMAINS_TOGGLE_LOADING'
