export const EMAILTEMPLATE_SHOW_RESET = 'EMAILTEMPLATE_SHOW_RESET'
export const EMAILTEMPLATE_SHOW_SET_ERROR = 'EMAILTEMPLATE_SHOW_SET_ERROR'
export const EMAILTEMPLATE_SHOW_SET_RETRIEVED = 'EMAILTEMPLATE_SHOW_SET_RETRIEVED'
export const EMAILTEMPLATE_SHOW_TOGGLE_LOADING = 'EMAILTEMPLATE_SHOW_TOGGLE_LOADING'
