export const ORDER_SHOW_RESET = 'ORDER_SHOW_RESET'
export const ORDER_SHOW_SET_ERROR = 'ORDER_SHOW_SET_ERROR'
export const ORDER_SHOW_SET_RETRIEVED = 'ORDER_SHOW_SET_RETRIEVED'
export const ORDER_SHOW_TOGGLE_LOADING = 'ORDER_SHOW_TOGGLE_LOADING'
