export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'
export const USER_PROFILE_SET_ERROR = 'USER_PROFILE_SET_ERROR'
export const USER_PROFILE_SET_RETRIEVED = 'USER_PROFILE_SET_RETRIEVED'
export const USER_PROFILE_TOGGLE_LOADING = 'USER_PROFILE_TOGGLE_LOADING'
