export const MEDIA_DELETE_RESET = 'MEDIA_DELETE_RESET'
export const MEDIA_DELETE_SET_ERROR = 'MEDIA_DELETE_SET_ERROR'
export const MEDIA_DELETE_SET_DELETED = 'MEDIA_DELETE_SET_DELETED'
export const MEDIA_DELETE_TOGGLE_LOADING = 'MEDIA_DELETE_TOGGLE_LOADING'
